pipeline {
    agent {
        docker { image 'node:22.15.1-alpine3.21' }
    }
    stages {
        stage('Deploy') {
            steps {
                sh 'node --eval "console.log(process.platform,process.env.CI)"'
            }
        }
    }
}
